### ISSUE TITLE
openSUSE和packman两个源都不能用

### ISSUE THREAD

**Issue by mcjoeng** [ideal/mirror#3]
repomd.xml列出的元数据根本对不上真实的元数据
例如 http://mirror.bjtu.edu.cn/opensuse/repositories/home%3a/Horst3180/openSUSE_Leap_42.1/repodata/repomd.xml 里面列出的是这三个：

560343eb2f1faa0ae672be18f0a52802a9ebc6a2531c22a739cc8250d0c70c10-filelists.xml.gz
d9afa1cec7874695ebb7f26a28f4ad30f833041bfc2c813d8c3d122b4f3492bd-other.xml.gz
bc672dfdd98c3bf6a38cc1c5311766ac0e84ec1115f4c179fbe6cf921e157132-primary.xml.gz

但在同一目录的数据是：
![2015-12-18 14-16-26](https://cloud.githubusercontent.com/assets/10485304/11890669/f6c68292-a591-11e5-8090-9d2edea05d72.png)
元数据没一个对应的上
对照opensuse官方的源很容易得出repomd.xml这个文件是错的，所以北交大的opensuse源不是从官方源同步的？

**Comment by mcjoeng** [comment]
/opensuse/repositories/ 这个目录里面的东西和 mirrorcatalogs.com 对应目录一模一样的都是错的，该不会是从 mirrorcatalogs.com 同步的吧。。。

**Comment by mcjoeng** [comment]
刚刚又查看了几个镜像发现全部都是错的。。。只有台湾的 http://free.nchc.org.tw/opensuse/repositories/是正确的。。。。

**Comment by ideal** [comment]
抱歉才看到这个issue，bjtu是从opensuse官方同步过来的，不知道现在这个问题还存在吗？

**Comment by ideal** [comment]
如果还有问题请到这里哈：https://github.com/AlynxZhou/bjtu-mirror-issues
