### ISSUE TITLE
希望增加 SteamOS 镜像

### ISSUE THREAD

**Issue by wbsdty331** [ideal/mirror#4]
SteamOS 是基于 Debian 的一个发行版
上游是 ：http://repo.steampowered.com/
由于国内网络原因加上Valve CDN的问题，下载安装光盘很缓慢，更新软件包也经常出错
希望添加，谢谢！

**Comment by ideal** [comment]
抱歉目前应该磁盘不够啦。

**Comment by ideal** [comment]
您可以考虑请求thu或者ustc增加SteamOs，谢谢。
