### ISSUE TITLE
Something confused about the daemon proccess.

### ISSUE THREAD

**Issue by Alecyrus** [ideal/mirror#6]
Thank you for your awesome tool. I just have some puzzles about the daemon process.
## #1
How can I know the daemon process's status ?
>I get the id from the pid file.

>![image](https://cloud.githubusercontent.com/assets/13865581/21488985/d5d0ee2c-cc20-11e6-800c-60bb496c70f1.png)

>then I run the command:
>![image](https://cloud.githubusercontent.com/assets/13865581/21488999/0132b348-cc21-11e6-8788-a1121341ba79.png)

>Is the pid correct ?

My suggestion is to add the option called "status" that can print the process's status on the screen. 

## #2 
 Another puzzle is that I get the error when I run the command for twice. 
> ![image](https://cloud.githubusercontent.com/assets/13865581/21489106/ca13cda6-cc21-11e6-9549-6263db95aa1c.png)

>I edit the source code, and I try to kill the process when the process catches the error?  And I failed to fix the error, the worse is I can NOT kill the daemon process on the condition that the pid is valid(IOError[2]). . 

My suggestion is to kill the previous process when we run the command for the second time. 

Many thanks.

**Comment by ideal** [comment]
Sorry for delay.

For question 1, if mirrord exits abnormally, then maybe the pid file still have old pid, thus `kill` will tell you that the process does not exist. However if you just want to kill mirrord, you can use `mirrord -s stop`. `mirrord -t` will give the status of task queue, for your suggestion, I can add some other info to this command. Thanks.

**Comment by ideal** [comment]
@Alecyrus For question 2, again, you can execute `mirrord -s stop` to stop old mirrord instance first, and then start it again, most times this will work well.

Can you give me the detail info of your error? Thank you.

**Comment by Alecyrus** [comment]
@ideal  I‘m  sorry, I probably can not reproduce  the error.  But I can remember that I try to kill the daemon   process manually after I found the command "mirror -s stop " didn't work.

**Comment by Alecyrus** [comment]
@ideal  I‘m  sorry, I probably can not reproduce  the error.  But I can remember that I try to kill the daemon   process manually after I found the command "mirror -s stop " didn't work.

**Comment by ideal** [comment]
Maybe more info needed.
