### ISSUE TITLE
centos镜像未同步，报告“Task: centos is still running and no timeout set, skipped”

### ISSUE THREAD

**Issue by cathywife** [ideal/mirror#7]
**问题描述：**
因为最近在关注CentOS 7.4的发布，想着去看一下内部源是否自动同步了CentOS 7.4，结果却发现更新日志最新是2017/9/9的。另外的一个epel源是正常的。查看status/task_status.json，似乎是推迟到了2017/9/16日更新，这是为什么？查看mirrord.log发现“Task: centos is still running and no timeout set, skipped”？像这种情况，要重启mirrod还是要设置超时之类的？

**相关配置：**
[root@~ mirror]# mirrord -v
mirrord: 0.6.8

[root@~ mirror]# mirrord -t
Task:logcleaner        	type:   System task	time: Sat Sep 16 01:00:00 2017
Task:centos            	type:   Normal task	time: Sat Sep 16 01:00:00 2017
Task:taskcleaner       	type:   System task	time: Sat Sep 16 02:00:00 2017
Task:epel              	type:   Normal task	time: Sat Sep 16 02:00:00 2017

[root@~ mirror]# ll /var/log/rsync/
total 3324
-rw-r--r-- 1 root root   53563 Sep  5 01:00 centos.log.2017-09-05
-rw-r--r-- 1 root root   79485 Sep  6 01:04 centos.log.2017-09-06
-rw-r--r-- 1 root root   53566 Sep  7 01:00 centos.log.2017-09-07
-rw-r--r-- 1 root root  112157 Sep  8 01:03 centos.log.2017-09-08
-rw-r--r-- 1 root root  159564 Sep  9 01:27 centos.log.2017-09-09
-rw-r--r-- 1 root root   37180 Sep  5 02:00 epel.log.2017-09-05
-rw-r--r-- 1 root root 1368120 Sep  6 05:58 epel.log.2017-09-06
-rw-r--r-- 1 root root   37081 Sep  7 02:00 epel.log.2017-09-07
-rw-r--r-- 1 root root  211104 Sep  8 02:15 epel.log.2017-09-08
-rw-r--r-- 1 root root   37105 Sep  9 02:00 epel.log.2017-09-09
-rw-r--r-- 1 root root  250337 Sep 10 02:26 epel.log.2017-09-10
-rw-r--r-- 1 root root  141833 Sep 11 02:09 epel.log.2017-09-11
-rw-r--r-- 1 root root  197220 Sep 12 02:20 epel.log.2017-09-12
-rw-r--r-- 1 root root  417374 Sep 13 03:39 epel.log.2017-09-13
-rw-r--r-- 1 root root   37207 Sep 14 02:00 epel.log.2017-09-14
-rw-r--r-- 1 root root  160385 Sep 15 02:06 epel.log.2017-09-15

[root@~ mirror]# cat status/task_status.json 
{"centos": {"status": 1, "date": "2017-09-09 01:00:00", "upstream": "mirrors.tuna.tsinghua.edu.cn::centos//", "schedule": "2017-09-16 01:00:00"}, "epel": {"status": 2, "schedule": "2017-09-16 02:00:00", "upstream": "mirrors.tuna.tsinghua.edu.cn::epel//", "date": "2017-09-15 02:06:15", "message": "Sync succeed", "exitcode": 0}}

[root@~ mirror]# grep -vE '^;|^$' mirror.ini 
[general]
emails     = xxx@yyy.zzz
loadlimit  = 4.0
httpconn   = 1200
logdir     = /var/log/rsync/
maxtasks   = 10
[centos]
upstream[] = mirrors.tuna.tsinghua.edu.cn 
command    = rsync
exclude    = --exclude .~tmp~/
time       = 00 01 * * *
rsyncdir   = centos/
localdir   = /sdb/mirrors/centos
args       = --bwlimit=512 -avPH --delete --delete-excluded --delete-after
twostage   = 0
timeout    = 0
priority   = 9
autoretry  = 1m
[epel]
upstream[] = mirrors.tuna.tsinghua.edu.cn 
command    = rsync
exclude    = --exclude .~tmp~/
time       = 00 02 * * *
rsyncdir   = epel/
localdir   = /sdb/mirrors/epel
args       = --bwlimit=512 -avPH --delete --delete-excluded --delete-after
twostage   = 0
timeout    = 0
priority   = 9
autoretry  = 1m

[root@~ mirror]# tail -n 50 /var/log/mirrord/mirrord.log 
09-12 02:20:28 [INFO    ][mirror.scheduler] Task: epel ended with return code 0, pid 30265
09-12 02:20:28 [INFO    ][mirror.scheduler] I am going to sleep, next waking up: Wed Sep 13 01:00:00 2017
09-13 01:00:00 [INFO    ][mirror.scheduler] I am waking up...
09-13 01:00:00 [INFO    ][mirror.scheduler] Starting task: centos ...
09-13 01:00:00 [INFO    ][mirror.scheduler] Task: centos is still running and no timeout set, skipped
09-13 01:00:00 [INFO    ][mirror.scheduler] I am going to sleep, next waking up: Wed Sep 13 02:00:00 2017
09-13 01:00:00 [INFO    ][systemtask      ] Running task: logcleaner
09-13 01:00:00 [INFO    ][logcleaner      ] Deleted log file: /var/log/rsync/epel.log.2017-09-02
09-13 01:00:00 [INFO    ][logcleaner      ] Deleted log file: /var/log/rsync/centos.log.2017-09-02
09-13 01:00:00 [INFO    ][systemtask      ] Finished task: logcleaner
09-13 02:00:00 [INFO    ][mirror.scheduler] I am waking up...
09-13 02:00:00 [INFO    ][mirror.scheduler] Starting task: epel ...
09-13 02:00:00 [INFO    ][mirror.scheduler] Task: epel begin to run with pid 10789
09-13 02:00:00 [INFO    ][mirror.scheduler] I am going to sleep, next waking up: Thu Sep 14 01:00:00 2017
09-13 02:00:00 [INFO    ][systemtask      ] Running task: taskcleaner
09-13 02:00:00 [INFO    ][systemtask      ] Finished task: taskcleaner
09-13 03:39:22 [INFO    ][mirror.scheduler] Task: epel ended with return code 0, pid 10789
09-13 03:39:22 [INFO    ][mirror.scheduler] I am going to sleep, next waking up: Thu Sep 14 01:00:00 2017
09-14 01:00:00 [INFO    ][mirror.scheduler] I am waking up...
09-14 01:00:00 [INFO    ][mirror.scheduler] Starting task: centos ...
09-14 01:00:00 [INFO    ][mirror.scheduler] Task: centos is still running and no timeout set, skipped
09-14 01:00:00 [INFO    ][mirror.scheduler] I am going to sleep, next waking up: Thu Sep 14 02:00:00 2017
09-14 01:00:00 [INFO    ][systemtask      ] Running task: logcleaner
09-14 01:00:00 [INFO    ][logcleaner      ] Deleted log file: /var/log/rsync/centos.log.2017-09-03
09-14 01:00:00 [INFO    ][logcleaner      ] Deleted log file: /var/log/rsync/epel.log.2017-09-03
09-14 01:00:00 [INFO    ][systemtask      ] Finished task: logcleaner
09-14 02:00:00 [INFO    ][mirror.scheduler] I am waking up...
09-14 02:00:00 [INFO    ][mirror.scheduler] Starting task: epel ...
09-14 02:00:00 [INFO    ][mirror.scheduler] Task: epel begin to run with pid 23523
09-14 02:00:00 [INFO    ][mirror.scheduler] I am going to sleep, next waking up: Fri Sep 15 01:00:00 2017
09-14 02:00:00 [INFO    ][systemtask      ] Running task: taskcleaner
09-14 02:00:00 [INFO    ][systemtask      ] Finished task: taskcleaner
09-14 02:00:28 [INFO    ][mirror.scheduler] Task: epel ended with return code 0, pid 23523
09-14 02:00:28 [INFO    ][mirror.scheduler] I am going to sleep, next waking up: Fri Sep 15 01:00:00 2017
09-15 01:00:00 [INFO    ][mirror.scheduler] I am waking up...
09-15 01:00:00 [INFO    ][mirror.scheduler] Starting task: centos ...
09-15 01:00:00 [INFO    ][mirror.scheduler] Task: centos is still running and no timeout set, skipped
09-15 01:00:00 [INFO    ][mirror.scheduler] I am going to sleep, next waking up: Fri Sep 15 02:00:00 2017
09-15 01:00:00 [INFO    ][systemtask      ] Running task: logcleaner
09-15 01:00:00 [INFO    ][logcleaner      ] Deleted log file: /var/log/rsync/epel.log.2017-09-04
09-15 01:00:00 [INFO    ][logcleaner      ] Deleted log file: /var/log/rsync/centos.log.2017-09-04
09-15 01:00:00 [INFO    ][systemtask      ] Finished task: logcleaner
09-15 02:00:00 [INFO    ][mirror.scheduler] I am waking up...
09-15 02:00:00 [INFO    ][mirror.scheduler] Starting task: epel ...
09-15 02:00:00 [INFO    ][mirror.scheduler] Task: epel begin to run with pid 4047
09-15 02:00:00 [INFO    ][mirror.scheduler] I am going to sleep, next waking up: Sat Sep 16 01:00:00 2017
09-15 02:00:00 [INFO    ][systemtask      ] Running task: taskcleaner
09-15 02:00:00 [INFO    ][systemtask      ] Finished task: taskcleaner
09-15 02:06:15 [INFO    ][mirror.scheduler] Task: epel ended with return code 0, pid 4047
09-15 02:06:15 [INFO    ][mirror.scheduler] I am going to sleep, next waking up: Sat Sep 16 01:00:00 2017

**Comment by ideal** [comment]
您好，某些时候一个任务的rsync可能会运行很久（可能是正常的，比如需要传输的文件很多；也可能是异常情况，由于某些原因rsync hang住一直未结束）。在这种情况下，到达预期的调度时间时，发现该任务的rsync已在运行，并且又没有设置任务的超时时间，那么不会再次调度。你可以给centos设置一个超时时间，比如`48h`表示两天，这样超时的时候rsync会被结束，以便下一次重新调度运行。

**Comment by cathywife** [comment]
目前我已设置超时24h，谢谢你的回复。另外，那个autoretry，重试的次数是如何定义，这里只是定义重试频率吧。

**Comment by ideal** [comment]
autoretry是只当某一次任务返回失败后，多少时间间隔后进行重试哈。目的是为了对于失败的情况，尽量短时候后进行重试，避免到达下次调度的时间太久了。所以这个autoretry也是一个时间单位，比如`3m`表示3分钟后。目前不支持定义次数，这个是对每次失败后对会起作用的。

**Comment by cathywife** [comment]
OK，谢谢。
