### ISSUE TITLE
可以请问下目前https://mirror.bjtu.edu.cn上每个被同步的镜像占用的磁盘空间是多少呢？

### ISSUE THREAD

**Issue by ppoffice** [ideal/mirror#9]
目前想要在学校建立一个镜像源，所以咨询一下所需的硬件设备。感谢各位的工作，希望这个小小的问题能得到解答。

**Comment by ideal** [comment]
您好，我记得总量应该是8T哈，还没满应该。具体@AlynxZhou 可以帮忙看下？

**Comment by AlynxZhou** [comment]
@ppoffice 现在用来挂mirror的一共有9T，已经用了大概8T，然后打算加一些硬盘空间。因为我回家了所以暂时也不知道每个镜像单独占的大小。
另外我要没记错的话阁下是几个Hexo主题的作者吧，之前有了解过。
